#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

nix build --no-link \
    .#checks.x86_64-linux.infrastructure \
    .#checks.x86_64-linux.manifests \
    .#checks.x86_64-linux.policy \
    .#checks.x86_64-linux.secretspec

shellcheck ci/run-with-progress.sh nix/pkgs/lucidity.sh tests/run.sh

lucidity=$(nix build --no-link --print-out-paths .#lucidity)
help=$("$lucidity"/bin/lucidity --help)
for interface in generate check build vm infra secrets mesh release; do
    grep -Eq "(^|[[:space:]])${interface}([[:space:]]|$)" <<<"$help" || {
        echo "lucidity help is missing the ${interface} interface" >&2
        exit 1
    }
done

if rg -n 'secretsmanager[[:space:]]+(get-secret-value|batch-get-secret-value)' \
    nix scripts tests --glob '!tests/run.sh'; then
    echo "direct Secrets Manager value retrieval is prohibited; use asm-exec" >&2
    exit 1
fi

if rg -n '^(ssh-ed25519|ssh-rsa|ecdsa-sha2-)' nix secretspec.toml; then
    echo "SSH public key material must be resolved from SecretSpec, not committed" >&2
    exit 1
fi

rg -q '^\[profiles\.coolify\]$' secretspec.toml
rg -q '^COOLIFY_API_TOKEN = \{ required = true \}$' secretspec.toml
rg -q '"team_id" => \$team->id' scripts/vm-integration.sh
rg -q 'LUCIDITY_TOKEN=' scripts/vm-integration.sh
rg -q "require '/var/www/html/bootstrap/app.php'" scripts/vm-integration.sh
rg -q 'docker exec coolify php -r "\$php_program"' scripts/vm-integration.sh
rg -q 'if type == "string" then fromjson else .' scripts/vm-integration.sh
rg -q 'coolify-worker-storage.service' nix/lib/mk-bootc-context.nix
rg -q 'Environment=COOLIFY_CURL_BIN=/usr/bin/curl' nix/lib/mk-bootc-context.nix
rg -q 'curl_bin=\$\{COOLIFY_CURL_BIN:-curl\}' scripts/bootstrap-controller.sh
rg -q 'mount --bind "\$source_path" "\$target_path"' nix/lib/mk-bootc-context.nix
rg -q 'lucidity-admin-authorized-key.service' nix/lib/mk-bootc-context.nix
rg -q '/etc/lucidity/admin-authorized-key.fingerprint' nix/pkgs/cloud-init-fixture.nix
rg -q '/etc/lucidity/vm-fixture' nix/lib/mk-bootc-context.nix
rg -Fq '#cloud-config' nix/pkgs/cloud-init-fixture.nix
rg -Fq 'secretspec run' nix/pkgs/cloud-init-fixture.nix
rg -Fq '#cloud-init-' scripts/vm-init.sh
if rg -q 'cat (>|>>) .*user-data' scripts/vm-init.sh; then
    echo "cloud-init structure must be generated by the locked Nix package" >&2
    exit 1
fi
if rg -q 'cat (>|>>) .*meta-data' scripts/vm-init.sh; then
    echo "cloud-init metadata must be generated by the locked Nix package" >&2
    exit 1
fi
rg -Fq '"${cloud_init_generator}" meta-data' scripts/vm-init.sh
rg -q 'systemctl is-active --quiet coolify-worker-storage.service' scripts/vm-validate.sh
if rg -q "localhost.*key" scripts/vm-integration.sh; then
    echo "Coolify integration must not depend on a private-key display name" >&2
    exit 1
fi
rg -Fq 'still running (${elapsed}s elapsed)' ci/run-with-progress.sh
rg -q 'name: Summarize integration build' .github/workflows/integration.yml
rg -q 'GITHUB_STEP_SUMMARY' .github/workflows/integration.yml
rg -q 'name: Upload integration failure diagnostics' .github/workflows/integration.yml
rg -q '^  required:$' .github/workflows/validate.yml
rg -q '^    name: required$' .github/workflows/validate.yml
rg -q 'needs: \[changes, static, role, mesh\]' .github/workflows/validate.yml
rg -q 'controller=true; worker=true; mesh=true' .github/workflows/validate.yml
rg -Fq 'nix run .#lucidity -- build controller' .github/workflows/integration.yml
rg -Fq 'nix run .#lucidity -- build worker' .github/workflows/integration.yml
if rg -q 'scripts/(build|validate-image)\.sh' .github/workflows/integration.yml; then
    echo "integration image builds must use the Nix-owned lucidity interface" >&2
    exit 1
fi
if rg -q 'scripts/(build|validate-image)\.sh' .github/workflows; then
    echo "GitHub image workflows must use the Nix-owned lucidity interface" >&2
    exit 1
fi
determinate_nix_action='DeterminateSystems/determinate-nix-action@61cbfe2efc2d4e7a8a6d56967c3c1058e846c858'
for workflow in \
    .github/workflows/ami-switch-benchmark.yml \
    .github/workflows/ami.yml \
    .github/workflows/integration.yml \
    .github/workflows/publish.yml; do
    install_line=$(rg -n -m1 -F "${determinate_nix_action}" "${workflow}" | cut -d: -f1)
    nix_line=$(rg -n -m1 'nix (run|build)' "${workflow}" | cut -d: -f1)
    if [[ -z ${install_line} || -z ${nix_line} || ${install_line} -ge ${nix_line} ]]; then
        echo "${workflow} must install pinned Determinate Nix before using nix" >&2
        exit 1
    fi
done
rg -Fq 'build controller|worker [--validate-only]' nix/pkgs/lucidity.sh
rg -q 'alejandra\.enable = true' nix/modules/outputs.nix
rg -q 'deadnix\.enable = true' nix/modules/outputs.nix
rg -q 'shellcheck\.enable = true' nix/modules/outputs.nix
rg -q 'actionlint\.enable = true' nix/modules/outputs.nix
if rg -n 'github:[^" ]+/[0-9a-f]{40}' flake.nix; then
    echo "flake input revisions belong in flake.lock so Determinate update-flake-lock can update them" >&2
    exit 1
fi
if rg -q 'package-ecosystem: nix' .github/dependabot.yml; then
    echo "Determinate update-flake-lock owns Nix input updates" >&2
    exit 1
fi
rg -q 'DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6' \
    .github/workflows/update-flake-lock.yml
if rg -n '^podman (image inspect|run)' tests/vm-role.sh; then
    echo "role validation must honor CONTAINER_ENGINE" >&2
    exit 1
fi

echo "Lucidity static acceptance checks passed"
