#!/usr/bin/env bash
set -Eeuo pipefail

token_file=${AWS_WCP_TOKEN_FILE:-/run/awssmatoken}

case "${1:-}" in
    start)
        install -o root -g aws-wcp-token -m 0640 /dev/null "${token_file}"
        head -c 32 /dev/urandom | sha256sum | cut -d ' ' -f 1 >"${token_file}"
        ;;
    stop)
        rm -f "${token_file}"
        ;;
    *)
        echo "usage: ${0##*/} start|stop" >&2
        exit 2
        ;;
esac
