{
  config,
  inputs,
  lib,
  ...
}: {
  imports = [inputs.terranix.flakeModule];

  den.classes.terranix.description = "OpenTofu infrastructure generated by Terranix";

  perSystem = {pkgs, ...}: {
    terranix.terranixConfigurations = {
      aws = {
        modules = [../../infra/aws.nix];
        extraArgs = {
          moduleRoot = ../../../tofu/modules;
          hostFacts =
            lib.mapAttrs (_: host: {
              inherit
                (host.lucidity)
                instanceType
                rootVolumeGiB
                overlayIPv4
                nebulaGroups
                ;
            })
            config.den.hosts.x86_64-linux;
        };
        terraformWrapper.package = pkgs.opentofu;
        workdir = ".lucidity/tofu/aws";
      };
      state = {
        modules = [../../infra/state.nix];
        extraArgs.stateRoot = ../../../tofu/modules/state-backend;
        terraformWrapper.package = pkgs.opentofu;
        workdir = ".lucidity/tofu/state";
      };
    };
  };
}
